config/routes.rb
Rails.application.routes.draw do
  root 'reservations#index'
  resources :reservations
  resources :reservations
  resources :tables

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :table
  validates_presence_of :start_time, :end_time, :table
  validate :validate_time_period, :validate_table_is_free,
           if: Proc.new { |r| r.start_time.present? && r.end_time.present? }
  scope :table, ->(id) { where(table_id: id) }

  def validate_time_period
    if start_time > end_time
      errors.add(:end_time, :time_period_negative)
    end
  end

  def validate_table_is_free
    if Reservation.table(table_id).where.not(id: self.id).
        exists?(start_time: start_time...end_time)
      errors.add(:start_time, :table_is_already_reserved)
    end
    if Reservation.table(table_id).where.not(id: self.id).
        exists?(end_time: start_time..end_time)
      errors.add(:end_time, :table_is_already_reserved)
    end
  end
end

app/models/table.rb
class Table < ActiveRecord::Base
  validates_presence_of :number
  validates_uniqueness_of :number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:table_id, :start_time, :end_time)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:number, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/layouts/_navigation.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Reservations
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: (:active if current_page?(controller: 'reservations')) }
          = link_to 'Reservations', reservations_path
        %li{class: (:active if current_page?(controller: 'tables')) }
          = link_to 'Tables', tables_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Reservations
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .container
      = yield

app/views/reservations/_form.html.haml
= bootstrap_form_for @reservation, inline_errors: false, html: { class: 'form-inline' } do |f|
  = f.alert_message 'Please fix the errors below.'

  = f.collection_select :table_id, Table.all, :id, :number
  = f.text_field :start_time, class: 'datetime-picker', append: glyph(:dashboard), |
  value: @reservation.start_time.to_formatted_s(:long) if @reservation.start_time.present?
  -#.input-group-addon
  -#  %span.glyphicon.glyphicon-dashboard
  = f.text_field :end_time, class: 'datetime-picker', append: glyph(:dashboard), |
    value: @reservation.end_time.to_formatted_s(:long) if @reservation.end_time.present?
  .form-group
    = f.submit 'Save'

app/views/reservations/edit.html.haml
%h1 Editing reservation

= render 'form'

= link_to 'Show', @reservation
\|
= link_to 'Back', reservations_path

app/views/reservations/index.html.haml
%h1 Listing reservations

%table.table
  %thead
    %tr
      %th Number
      %th Start time
      %th End time
      %th.actions

  %tbody
    - @reservations.each do |reservation|
      %tr
        %td= reservation.table.number
        %td= reservation.start_time.to_formatted_s :short
        %td= reservation.end_time.to_formatted_s :short
        %td
          = link_to glyph(:eye_open), reservation
          = link_to glyph(:pencil), edit_reservation_path(reservation)
          = link_to glyph(:remove), reservation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Reservation', new_reservation_path

app/views/reservations/new.html.haml
%h1 New reservation

= render 'form'

= link_to 'Back', reservations_path

app/views/reservations/show.html.haml
%p#notice= notice
%ul.list-group
  %li.list-group-item
    %span.badge= @reservation.table.number
    Table:
  %li.list-group-item
    %span.badge= @reservation.start_time.to_formatted_s :short
    Start:
  %li.list-group-item
    %span.badge= @reservation.end_time.to_formatted_s :short
    End:
  %li.list-group-item
    %span.badge= @reservation.created_at.to_formatted_s :short
    Created at:
  %li.list-group-item
    %span.badge= @reservation.updated_at.to_formatted_s :short
    Updated at:

= link_to 'Edit', edit_reservation_path(@reservation)
\|
= link_to 'Back', reservations_path

app/views/tables/_form.html.haml
= form_for @table, html: {class: 'form-horizontal'} do |f|
  - if @table.errors.any?
    #error_explanation
      %h2= "#{pluralize(@table.errors.count, "error")} prohibited this table from being saved:"
      %ul
        - @table.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :number, {class: 'col-sm-2 control-label'}
    .col-sm-10
      = f.number_field :number, class: 'form-control'
  .form-group
    = f.label :notes, {class: 'col-sm-2 control-label'}
    .col-sm-10
      = f.text_area :notes, class: 'form-control'
  .form-group
    = f.submit 'Save'

app/views/tables/edit.html.haml
%h1 Editing table

= render 'form'

= link_to 'Show', @table
\|
= link_to 'Back', tables_path

app/views/tables/index.html.haml
%h1 Listing tables

%table.table
  %thead
    %tr
      %th Number
      %th Notes
      %th
      %th
      %th

  %tbody
    - @tables.each do |table|
      %tr
        %td= table.number
        %td= table.notes
        %td
          = link_to glyph(:eye_open), table
          = link_to glyph(:pencil), table
          = link_to glyph(:remove), table, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Table', new_table_path

app/views/tables/new.html.haml
%h1 New table

= render 'form'

= link_to 'Back', tables_path

app/views/tables/show.html.haml
%p#notice= notice
%ul.list-group
  %li.list-group-item
    %span.badge= @table.number
    Number:
  %li.list-group-item
    %span.badge= @table.notes
    Notes:
  %li.list-group-item
    %span.badge= @table.created_at.to_formatted_s :short
    Created at:
  %li.list-group-item
    %span.badge= @table.updated_at.to_formatted_s :short
    Updated at:

= link_to 'Edit', edit_table_path(@table)
\|
= link_to 'Back', tables_path